options:
  tomcat-user:
    type: string
    default: "tomcat8"
    description: "The user added to tomcat"
  tomcat-passwd:
    type: string
    default: "tomcat8"
    description: "The tomcat user password"
  install-admin:
    type: boolean
    default: True
    description: "Include the tomcat8-admin package for administration"
#  boolean-option:
#    type: boolean
#    default: False
#    description: "A short description of the configuration option"
#  int-option:
#    type: int
#    default: 9001
#    description: "A short description of the configuration option"

